// Images ------------------------
import chessImage from './Assets/chess.png';


const Data = [
    {
        id: "1",
        title: "Testing",
        content: "Pellentesque habitant morbi tristique senectus et netus et malesuada fames ac turpis egestas. Vestibulum tortor quam, feugiat vitae, ultricies eget, tempor sit amet, ante. Donec eu libero sit amet quam egestas semper. Aenean ultricies mi vitae est. Mauris placerat eleifend leo",
        type: "web",
        type_display: "Web Application",
        image: chessImage,
        language: ["test", "test"],
        framework: ["test","test"],
        organization: "School Project",
        created_date: "3 Janurary 2024",
        updated_date: "4 Janurary 2024",
        demo: "https://www.youtube.com/watch?v=lXA0ATF12JY",
        code: "https://www.youtube.com/watch?v=lXA0ATF12JY",
    },
    {
        id: "2",
        title: "Testing",
        content: "Testing",
        type: "app",
        type_display: "Android Application",
        image: chessImage,
        language: ["test", "test"],
        framework: ["test","test"],
        organization: "Personal Project",
        created_date: "3 Janurary 2024",
        updated_date: "4 Janurary 2024",
        demo: "https://www.youtube.com/watch?v=lXA0ATF12JY",
        code: "https://www.youtube.com/watch?v=lXA0ATF12JY",
    },
    {
        id: "3",
        title: "Testing2",
        content: "Testing2",
        type: "web",
        type_display: "Web Application",
        image: chessImage,
        language: ["test", "test"],
        framework: ["test","test"],
        organization: "School Project",
        created_date: "3 Janurary 2024",
        updated_date: "4 Janurary 2024",
        demo: "https://www.youtube.com/watch?v=lXA0ATF12JY",
        code: "https://www.youtube.com/watch?v=lXA0ATF12JY",
    },
    {
        id: "4",
        title: "Testing2",
        content: "Testing2",
        type: "web",
        type_display: "Web Application",
        image: chessImage,
        language: ["test", "test"],
        framework: ["test","test"],
        organization: "School Project",
        created_date: "3 Janurary 2024",
        updated_date: "4 Janurary 2024",
        demo: "https://www.youtube.com/watch?v=lXA0ATF12JY",
        code: "https://www.youtube.com/watch?v=lXA0ATF12JY",
    },
    {
        id: "5",
        title: "Testing2",
        content: "Testing2",
        type: "web",
        type_display: "Web Application",
        image: chessImage,
        language: ["test", "test"],
        framework: ["test","test"],
        organization: "School Project",
        created_date: "3 Janurary 2024",
        updated_date: "4 Janurary 2024",
        demo: "https://www.youtube.com/watch?v=lXA0ATF12JY",
        code: "https://www.youtube.com/watch?v=lXA0ATF12JY",
    },
    {
        id: "6",
        title: "Testing2",
        content: "Testing2",
        type: "web",
        type_display: "Web Application",
        image: chessImage,
        language: ["test", "test"],
        framework: ["test","test"],
        organization: "School Project",
        created_date: "3 Janurary 2024",
        updated_date: "4 Janurary 2024",
        demo: "https://www.youtube.com/watch?v=lXA0ATF12JY",
        code: "https://www.youtube.com/watch?v=lXA0ATF12JY",
    },
]

export default Data;